# Generated by Django 3.1 on 2020-08-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schemes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('O', 'Other'), ('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('name', models.CharField(max_length=120)),
                ('age', models.IntegerField()),
                ('location', models.CharField(max_length=120)),
                ('income', models.BigIntegerField()),
                ('family_size', models.IntegerField()),
                ('only_child', models.BooleanField()),
                ('only_girl_child', models.BooleanField()),
                ('refugee', models.BooleanField()),
                ('caste', models.CharField(max_length=120)),
                ('religion', models.CharField(max_length=120)),
                ('minorities', models.CharField(max_length=120)),
                ('language', models.CharField(max_length=120)),
                ('military_experience', models.BooleanField()),
                ('government_officials', models.BooleanField()),
                ('disability', models.BooleanField()),
                ('msme', models.BooleanField()),
                ('daily_wage_workers', models.BooleanField()),
            ],
        ),
    ]
