# Generated by Django 3.1 on 2020-08-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemes',
            name='scheme_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
