# Generated by Django 3.1 on 2020-08-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0002_schemes_scheme_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemes',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schemes',
            name='caste',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='schemes',
            name='family_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schemes',
            name='income',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schemes',
            name='language',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='schemes',
            name='minorities',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='schemes',
            name='religion',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
