# Generated by Django 3.1 on 2020-08-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='department',
            field=models.CharField(default='', max_length=20),
        ),
    ]
