# Generated by Django 3.1 on 2020-08-16 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_volunteer_department'),
        ('volunteers', '0003_auto_20200816_1523'),
    ]

    operations = [
    ]
