# Generated by Django 3.1 on 2020-08-16 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_auto_20200817_0302'),
        ('volunteers', '0004_merge_20200816_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteermember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enduser', to='members.member'),
        ),
    ]
