# Generated by Django 3.1 on 2020-08-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('dob', models.DateField()),
                ('income', models.IntegerField()),
                ('family_size', models.IntegerField()),
                ('gender', models.CharField(max_length=7)),
                ('location', models.CharField(max_length=120)),
            ],
        ),
    ]
