# Generated by Django 3.1 on 2020-08-16 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0004_auto_20200816_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='family_size',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('WOULD NOT LIKE TO DISCLOSE', 'Would Not Like TO Disclose')], default='WOULD NOT LIKE TO DISCLOSE', max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='income',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL),
        ),
    ]
