# Generated by Django 3.1 on 2020-08-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0004_auto_20200816_1904'),
        ('members', '0006_auto_20200816_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='schemes',
            field=models.ManyToManyField(default=None, to='schemes.Schemes'),
        ),
    ]
