# Generated by Django 3.1 on 2020-08-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0004_auto_20200816_1904'),
        ('members', '0007_member_schemes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='schemes',
            field=models.ManyToManyField(default=None, related_name='applied_schemes', to='schemes.Schemes'),
        ),
    ]
