# Generated by Django 3.1 on 2020-08-17 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_auto_20200817_0302'),
        ('members', '0008_auto_20200817_0140'),
    ]

    operations = [
    ]
